/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nicola' at '07/07/16 11:17' with Gradle 2.13
 *
 * @author Nicola, @date 07/07/16 11:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
